export const endpoints = {
    resources: {
        getAll: '/resources',
        getById: (id: string) => `/resources/${id}`,
        getByType: (type: string) => `/resources/type/${type}`,
        create: '/resources',
        update: (id: string) => `/resources/${id}`,
        delete: (id: string) => `/resources/${id}`,
        getHistory: (id: string) => `/resources/${id}/history`,
    },
    alerts: {
        getAll: '/alerts',
        getUnacknowledged: '/alerts/unacknowledged',
        getByResourceId: (resourceId: string) => `/alerts/resource/${resourceId}`,
        getById: (id: string) => `/alerts/${id}`,
        create: '/alerts',
        acknowledge: (id: string) => `/alerts/${id}/acknowledge`,
        delete: (id: string) => `/alerts/${id}`,
        clearAcknowledged: '/alerts/acknowledged/clear',
    },
    resupply: {
        getAll: '/resupply',
        getByStatus: (status: string) => `/resupply/status/${status}`,
        getByResourceType: (type: string) => `/resupply/resource-type/${type}`,
        getById: (id: string) => `/resupply/${id}`,
        create: '/resupply',
        update: (id: string) => `/resupply/${id}`,
        delete: (id: string) => `/resupply/${id}`,
        approve: (id: string) => `/resupply/${id}/approve`,
        cancel: (id: string) => `/resupply/${id}/cancel`,
    },
    rovers: {
        getAll: '/rovers',
        getById: (id: string) => `/rovers/${id}`,
        create: '/rovers',
        update: (id: string) => `/rovers/${id}`,
        delete: (id: string) => `/rovers/${id}`,
    },
    analytics: {
        getTrends: '/analytics/trends',
        getStats: '/analytics/stats',
        detectAnomalies: '/analytics/anomalies/detect',
        getAnomalies: '/analytics/anomalies',
    },
};
